[build]
  base = "conference-search"
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_TICKETMASTER_API_KEY = "4XDdUqBLaB7GOTLY5GjHyg7kKxtzUtZG"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
