[build]
  base = "conference-search"
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_EVENTBRITE_API_KEY = "CP3VLNL5VAJCDMRGCOOH"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
